<metadata>
  <groupId>${group/'.'}</groupId>
  <artifactId>${name}</artifactId>
  <version>${latest}</version>
  <versioning>
    <versions>
${versions*metadata_version/}
    </versions>
  <lastUpdated>${stamp}</lastUpdated>
  </versioning>
</metadata>